version: '3.8'

services:
  # Express 服务
  app:
    image: docker.io/library/node:18-alpine
    build: .              # 使用当前目录的 Dockerfile 构建
    container_name: ai-assistant-server
    ports:
      - "3000:3000"       # 主机端口:容器端口
    environment:
      - NODE_ENV=production
    restart: on-failure
    volumes:
      - ./logs:/vol1/1000/ai-assistant/server/logs  # 挂载日志目录（可选）
      - ./:/vol1/1000/ai-assistant/server